#!/bin/bash -l
#SBATCH -p debug # change this option for non-debug runs
#SBATCH -t 00:10:00
#SBATCH -N 24
#SBATCH -o mpi24.%j.stdout
#SBATCH -e mpi24.%j.error

srun -n 192 ./mpi -n 2222 -o mpi192.txt
srun -n 96 ./mpi -n 2222 -o mpi96.txt
